grimmApp.service("Persons", ['$http', 'BASE_URL', function ($http, BASE_URL) {
    var serviceBackend = BASE_URL + '/api/';

    this.all = function (itemsPerPage, page, orderBy, orderByDirection, autoGenerated) {

        var params = {};

        if (typeof itemsPerPage != 'undefined') {
            params.items_per_page = itemsPerPage;
        }

        if (typeof page != 'undefined') {
            params.page = page;
        }

        if (typeof orderBy != 'undefined') {
            params.order_by = orderBy;
        }

        if (typeof orderByDirection != 'undefined') {
            params.order_by_direction = orderByDirection;
        }

        if (typeof autoGenerated != 'undefined') {
            params.auto_generated = autoGenerated ? 1 : 0;
        }

        return $http.get(serviceBackend + 'persons', {
            params: params
        });
    };

    this.search = function (name) {
        return $http.post(serviceBackend + 'persons/search', {
            "name": name
        });
    };

    this.searchAhead = function (name) {
        return $http.post(serviceBackend + 'persons/search', {
            "name": name,
            "ahead": 1
        });
    }

    this.autoGenerate = function (name) {
        return $http.post(serviceBackend + 'persons', {
            name_2013: name,
            auto_generated: 1
        });
    }
}]);
