grimmApp.controller('personsController', ['$scope', 'Persons', function ($scope, Persons) {

    $scope.mode = 'index';
    $scope.persons = [];
    $scope.currentPerson = {};

    $scope.itemsPerPage = 25;
    $scope.currentPage = 1;
    $scope.itemsPerPageOptions = [10, 15, 20, 25, 30, 35, 40, 50, 60, 70, 80, 90, 100, 150];

    $scope.currentOrderBy = 'received_letters_count';
    $scope.currentOrderByDirection = 'desc';

    $scope.autoGenerated = false;

    $scope.reload = function () {

        console.log($scope);

        var itemsPerPage = $scope.itemsPerPage;
        var currentPage = $scope.currentPage;
        var currentOrderBy = $scope.currentOrderBy;
        var currentOrderByDirection = $scope.currentOrderByDirection;
        var autoGenerated = $scope.autoGenerated;

        Persons.all(itemsPerPage, currentPage, currentOrderBy, currentOrderByDirection, autoGenerated).success(function (data) {
            $scope.persons = data;
        });
    }

    $scope.reload();

    $scope.index = function () {
        $scope.mode = 'index';
        $scope.currentPerson = {};
    };

    $scope.show = function (person) {
        $scope.mode = 'show';
        $scope.currentPerson = person;
    };

    $scope.orderBy = function(field) {
        if($scope.currentOrderBy != field) {
            $scope.currentOrderBy = field;
            $scope.currentOrderByDirection = 'asc';
        } else {
            $scope.currentOrderByDirection = $scope.currentOrderByDirection == 'asc' ? 'desc' : 'asc';
        }

        $scope.reload();
    }
}]);
